#!/usr/bin/env sh

IMAGE="researchshare_backend"
TAG="latest"

if [ "$(id -nG | grep docker)" = "" ] && [ "$(whoami)" != "root" ]; then
    echo "Cannot run docker commands, because there is no proper rights"
    exit
fi

if [ "$(docker images | grep ${IMAGE})" = "" ] || [ "$1" = "--build" ]; then
    docker build . -t ${IMAGE}:${TAG}
fi

docker run --rm --init ${IMAGE}:${TAG}
